### PR TITLE
Aug 19 spark release

### PR DESCRIPTION
**Pull request by datwright**
New spark release that is just apache/spark's master branch (~2 weeks back) with all of our custom code placed into a single commit at the end.   This way our changes aren't buried in the history.

Includes the commit that @dterror wants
https://github.com/Shopify/spark/commit/33bae585d4cb25aed2ac32e0d1248f78cc65318b

@Shopify/data-modelling

### CODE REVIEW

**Comment by dterror** [comment]
thanks @datwright

**Comment by solackerman** [comment]
:+1:

**Comment by datwright** [comment]
Verified that packserv builds correctly http://pack.chi.shopify.com/

**Comment by angelini** [comment]
The two code removals can be done in a separate PR.

This LGTM

Are there any big changes we should be aware of?

**Comment by datwright** [comment]
Closing this, will re-open in another PR

**Pull request closed without merging**
