### PR TITLE
Update py4j to 0.9.

### PR DESCRIPTION
**Pull request by kevincox**
Fixes https://github.com/Shopify/starscream/issues/6739

@solackerman @angelini @kmtaylor-github

### CODE REVIEW

**Comment by angelini** [comment]
:+1: :+1:

**Comment by kevincox** [comment]
Upstream https://github.com/apache/spark/pull/8722

**Comment by solackerman** [comment]
:+1:

**Comment by kevincox** [comment]
Closing because there are code changes required and they are already being handled upstream.

As a temporary workaround we could "backport" (copy) that one function into the archive that we use. Thoughts?

**Pull request closed without merging**
