### PR TITLE
add spark streaming requirements to pomfile

### PR DESCRIPTION
**Pull request by manygrams**
For review @airhorns @JasonMWhite 

This adds the dependancies for Spark streaming. Hoping to get this in before tomorrow's upgrade!

### CODE REVIEW

**Comment by JasonMWhite** [comment]
This is how I got it running locally, but the online documentation makes it sound like this is unnecessary for Python (with spark-submit). Not sure about with the programmatic approach we use.

**Comment by airhorns** [comment]
I believe you @JasonMWhite , i'm cool with this

**Comment by manygrams** [comment]
Good to merge?

**Comment by JasonMWhite** [comment]
:ship: :package:

**Comment by manygrams** [comment]
✨

**Pull request merged**
