### PR TITLE
Orens problematic bump

### PR DESCRIPTION
**Pull request by orenmazor**
this is @airhorns big branch that is rebased on our master. 

I've been testing it with random jobs with my laptop as the driver. not seeing any issues at the moment.

@Shopify/data-engineers 

WIP

### CODE REVIEW

**Comment by airhorns** [comment]
Is this guy deployed somewhere?

**Comment by orenmazor** [comment]
yeah the jar is on hdfs. i've run a bunch of jobs against it.

**Comment by orenmazor** [comment]
@airhorns if we came up with a way to do a cascading deploy, we'll complete @camilo's dream of ring deploys before him

**Comment by airhorns** [comment]
HAHA yesssss

**Comment by camilo** [comment]
pfft ring deploys on non-critical systems ... :P

**Pull request merged**
