### PR TITLE
deploy staging spark jar

### PR DESCRIPTION
**Pull request by orenmazor**
in my ongoing quest to come up with a sane method of rolling out big spark updates without disruption, I've got this current theory:

1. ```cap staging deploy:upload_to_hdfs``` puts the new spark staging jar into hdfs.
2. you then go to azkaban and under the staging-starscream project, you have the same schedule as production, but where all the jobs are unscheduled. you can queue up a bunch of jobs that are normally critical and are too big to fail.

questions:
1. do we want these jobs writing to frontroom?
2. …

@Shopify/data-engineers

### CODE REVIEW

**Comment by yagnik** [comment]
@orenmazor no these shouldn't write to frontroom ever because that breaks the history of jobs.
I prefer manually executing jobs with different frontroom location

**Comment by orenmazor** [comment]
Yeah right now that's already possible with test_spark_jar.

I'd just like something we can kick start overnight that will run all our
jobs and verify our schedule is good to go. Otherwise we'd have to manually
test everything.

**Comment by yagnik** [comment]
+1 to running the whole suite overnight but I'd like to automate staging setup as opposed to merging with frontroom.
We could make changes to scheduler.py so that a staging deploy will drop a different "spark jar" and then change paths to be /tmp/staging/<path> and run the whole schedule on it.
Thoughts?

**Comment by orenmazor** [comment]
I'm super in favour of that. its sort of what i've been doing in my tests (just push all output to /tmp/oren), but we'd need to make sure none of the loaders run.

we already have a staging scheduler setup in azkaban too

**Comment by airhorns** [comment]
Dudes there's no way we can run every job over night... we are already at 100% utilization! I think we could do some kind of beta arrangement where some low priority jobs are marked as staging jobs, and inherit an extended spark config that we can then test them using a new jar or dynamic scaling properties or whatever. But I don't think we can just run the whole schedule again, especially if it isn't into the frontroom, what a waste! 

Also, I bet this doesn't work for a couple reasons:
 - you are uploading the jar from /u/apps/spark/current which is by definition the production version and means to deploy staging we'd need to deploy a new version to production (oops)
 - Packserv doesn't compile jars for anything other than master so we can't get it from there either

I think the best way to test isn't to upload via the production deploy sequence but instead just use the uploader built into spark when you just don't specify spark.yarn.jar?

**Comment by orenmazor** [comment]
yeah i know definitely. @udnay suggested forever ago that we should have some lower prio jobs duplicated into this testing schedule and thats kind of what i'm thinking

**Comment by airhorns** [comment]
Gonna close this in favour of the other staging stuff we've been talking about in starscream land.

**Pull request closed without merging**
