### PR TITLE
Re-add the statsd metrics sink 

### PR DESCRIPTION
**Pull request by airhorns**
When we moved Spark inside the Starscream driver docker container, we lost all the configs that were managed by chef (because chef doesn't bootstrap the docker container environment in any way). I screwed this up and forgot to port one config item over: the `metrics.properties` template.

Here's what it used to look like when we ran on `spark-etl1`: https://github.com/Shopify/cookbooks/blob/master/cookbooks/spark/templates/default/metrics.properties.erb

This just adds it to the spark version that packserv builds such that everyone will get it, devs and production alike. This means in prod we should start getting spark metrics again! Wootzone!

It looks like we are still getting a trickle of these stats which is why we never noticed they were broken: https://app.datadoghq.com/metric/explorer?live=true&page=0&is_auto=false&from_ts=1443640720647&to_ts=1444245520647&tile_size=m&exp_metric=spark.driver.jvm.heap.used&exp_scope=&exp_agg=sum&exp_row_type=metric . You'll notice all these stats are only from the driver, which I think confirms my suspicion that they are only from the spark contexts that are ever started outside the docker container. This actually still happens at one point: on deploy! We run the script/upload_package and whatnot outside docker containers, which is only fine because we haven't removed all the excess chef-deposited spark cruft from the driver nodes.

I want these metrics from the workers (note the absence of spark.worker.* metrics in :dog:) and all driver contexts.

@JasonMWhite @angelini @kmtaylor-github @dklassen ok with you?

### CODE REVIEW

**Comment by kmtaylor-github** [comment]
:heavy_plus_sign: :microscope: = :tada:

**Comment by angelini** [comment]
:tophat: 
:horse:

**Comment by JasonMWhite** [comment]
:100:

**Comment by airhorns** [comment]
Hey @damnMeddlingKid, this is a thing which I never shipped which you may want to on the new Spark build chain. /cc @angelini

**Pull request closed without merging**
