### PR TITLE
Update spark 2015-09-11

### PR DESCRIPTION
**Pull request by kevincox**
This fixes [a bug with writing dataframes with decimal types to JSON](https://issues.apache.org/jira/browse/SPARK-10298) which will allow us to store our surrogate keys.

@angelini @solackerman @kmtaylor-github

### CODE REVIEW

**Comment by kmtaylor-github** [comment]
Check with @datwright if you haven't already. He was trying to clean up the way we did this last update.

**Comment by solackerman** [comment]
+1 to Karl's comment, I don't remember the details, but it went back and forth.

**Comment by kevincox** [comment]
Cool, it would be awesome to have a more automatic update process :+1:

**Comment by datwright** [comment]
So we decided to stay 2 weeks behind master in a compromise between pulling in the very latest code and being on a release branch.

So Aug 28th should be the latest commit you're pulling in from spark master. 

The other part I was trying to clean up didn't go so well because of the way we've been merging in master since the beginning instead of rebasing, and that's basically unrecoverable at this point without blasting away all the old commits and creating a new master commit (which I did initially but that was decided against).   It would have also allowed us to jump to a release branch.

Anyway, just do this again without all the bleeding edge commits and it should be :+1:

**Comment by datwright** [comment]
Sorry, and the other thing you should do is scan ahead in the following 2 weeks and see if there are any emergency fixes.  If so, then hold off on the upgrade until that patch becomes 2 weeks old

**Comment by kevincox** [comment]
Ok, I'm closing this and will create a new PR.

**Pull request closed without merging**
