### PR TITLE
Update spark to 2015-08-28

### PR DESCRIPTION
**Pull request by kevincox**
This fixes [a bug with writing dataframes with decimal types to JSON](https://issues.apache.org/jira/browse/SPARK-10298) which will allow us to store our surrogate keys.

@angelini @solackerman @kmtaylor-github @datwright

### CODE REVIEW

**Comment by datwright** [comment]
Did you scan the commits for anything interesting / relevant to us? 

Also, please hold off on releasing because Friday afternoon spark releases aren't always fun on Saturday.

**Comment by angelini** [comment]
LGTM. And I agree with @datwright, let's hold this until Monday

**Comment by kevincox** [comment]
I did scan the commits (and the ones up to current) and didn't see anything interesting. I'll merge this on monday if you guys are happy with it.

**Comment by kevincox** [comment]
I'm going to create a more up to date PR for monday.

**Pull request closed without merging**
